### ISSUE TITLE
Back to Work

### ISSUE THREAD

**Issue by RenCloud** [RenCloud/scs-sdk-plugin#88]
Over the last month, some work piled up. This will be a state issue.

- [ ] #87  update sdk to lates version (currently experimental/beta version of the game)
- [ ] #82 need to be checked and possible merged
- [ ] cleanup of issues (some can be combined / deleted)
- [ ] #86 seems to be not possible, close comment needed
- [ ] #85, need to refresh my information to say something to that 
- [ ] #84, seems to be a great Idea, will be part of the overall 1.11 Update
    - [ ]  as folloup/together #81 
    - [ ] also here #58, #54, #31
- [ ] combined linux tickets, #28 #75  #79 #83, no external library will be used (that's the current plan), but it should be more or less painless change if you want to use a library like in #83
- [ ] #78 through lower refresh rate events are unreliable, hotfix here and proper fix with #34, try to fix #38 and #37
- [ ] #73, #65, #55  need to be rechecked
- [ ] #46 
- [ ] #35
